In [2]:
import numpy as np

In [3]:
nparr = np.array([[1,2,3,4]])

In [4]:
nparr

array([[1, 2, 3, 4]])

In [7]:
np.int0(nparr)

array([[1, 2, 3, 4]], dtype=int64)

In [8]:
np.int8(nparr)

array([[1, 2, 3, 4]], dtype=int8)

In [9]:
np.int64(nparr)

array([[1, 2, 3, 4]], dtype=int64)

In [10]:
np.int32(nparr)

array([[1, 2, 3, 4]])