In [2]:
import numpy as np

In [3]:
nparr = np.array([[1,2,3,4]])

In [4]:
nparr

array([[1, 2, 3, 4]])

In [7]:
np.int0(nparr)

array([[1, 2, 3, 4]], dtype=int64)

In [8]:
np.int8(nparr)

array([[1, 2, 3, 4]], dtype=int8)

In [9]:
np.int64(nparr)

array([[1, 2, 3, 4]], dtype=int64)

In [10]:
np.int32(nparr)

array([[1, 2, 3, 4]])

In [1]:
import tensorflow as tf

In [2]:
v1 = tf.constant([[2],[3]])
#创建一个常量v1，这是一个2行，1列的矩阵
v2 = tf.constant([[2,3]])
#创建一个常量v2，这是一个1行，2列的矩阵

In [3]:
product = tf.matmul(v1,v2)#创建一个矩阵的乘法，它不会马上执行

In [4]:
print(product)#它是乘法本身

Tensor("MatMul:0", shape=(2, 2), dtype=int32)


In [5]:
#定义一个会话
sess = tf.Session()
#运算乘法，得到结果
result = sess.run(product)
#打印结果
print(result)
#关闭会话
sess.close()

[[4 6]
 [6 9]]


In [6]:
product2 = tf.matmul(v2,v1)

In [7]:
sess = tf.Session()
result = sess.run(product2)
print(result)
sess.close()

[[13]]
